---
title: "2021 Group Project"
author: "MOHIT BADHAN"
date: "2024-03-09"
output: 
  html_document: 
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library("tidyverse")
library("janitor")
library("lubridate")
```

```{r}
happy <- read_csv("dataa/2021.csv") %>% clean_names()
happy
```


### ANY NA's

```{r}
anyNA(happy)
```

### Number of countries per region

```{r}
table(happy$regional_indicator)
```
```{r}
happy %>%
  group_by(regional_indicator) %>%
  summarize(mean_happiness=mean(ladder_score, na.rm=T)) %>%
  ggplot(aes(x=regional_indicator, fill=mean_happiness))+ 
  geom_bar(position="dodge")+
  coord_flip()
```

```{r}
happy %>%
  group_by(regional_indicator) %>%
  summarize(mean_gdp=mean(logged_gdp_per_capita, na.rm=T)) %>%
  ggplot(aes(x=regional_indicator, y=mean_gdp, fill= mean_gdp))+ 
  geom_col()+
  coord_flip()
```

```{r}
happy %>%
  group_by(regional_indicator) %>%
  summarize(mean_life_expectancy=mean(healthy_life_expectancy, na.rm=T)) %>%
  ggplot(aes(x=regional_indicator, y=mean_life_expectancy, fill= regional_indicator))+ 
  geom_col()+
  coord_flip()
```

```{r}
happy %>%
  group_by(regional_indicator) %>%
  summarize(mean_support=mean(social_support, na.rm=T)) %>%
  ggplot(aes(x=regional_indicator, y=mean_support, fill=regional_indicator))+ 
  geom_col()+
  coord_flip()
```


Highest Ladder Score 

```{r}
happy %>%
  select(country_name, ladder_score) %>%
  arrange(desc(ladder_score))
```

Lowest Ladder Score 

```{r}
happy %>%
  select(country_name, ladder_score) %>%
  arrange(ladder_score)
```

Top 5 countries for life expectancy

```{r}
happy %>%
  select(country_name, healthy_life_expectancy) %>%
  arrange(desc(healthy_life_expectancy))
```

Range of Freedom to Make Life Choices by Region

```{r}
happy %>% 
  ggplot(aes(x=regional_indicator, y=freedom_to_make_life_choices))+
  geom_boxplot()+
  coord_flip()+
  scale_y_log10()+
  labs(title="Observations by Region",
       x="Region",
       y="Freedom")
```


```{r}
happy %>%
  select(country_name,logged_gdp_per_capita) %>%
  arrange(desc(logged_gdp_per_capita))
```

```{r}
happy %>%
  filter(!ladder_score=="NA") %>%
  summarize(mean_happiness_score=mean(logged_gdp_per_capita), 
  min_happiness_score=min(logged_gdp_per_capita), 
  max_happiness_score=max(logged_gdp_per_capita), 
  total=n())
```

```{r}
happy %>%
  filter(country_name=="Finland") %>%
  select(ladder_score, logged_gdp_per_capita, healthy_life_expectancy, social_support)
```

```{r}
happy %>%
  filter(country_name=="Afghanistan") %>%
  select(ladder_score, logged_gdp_per_capita, healthy_life_expectancy, social_support) 
```

```{r}
happy %>%
  filter(country_name=="United States") %>%
  select(ladder_score, logged_gdp_per_capita, healthy_life_expectancy, social_support) 
```






