---
title: "LAB6WARMUP"
output: html_document
date: "2024-01-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```

```{r}
library("dplyr")
```


```{r}
bison <- read.csv("data/bison.csv")
```

```{r}
dim(bison)
```
```{r}
colnames(bison)
```


```{r}
str(bison)
```

```{r}
bis <- select(bison, "data_code","animal_sex", "animal_weight", "animal_yob")
```

```{r}
bis %>%
  select(animal_yob) %>%
  filter(between(animal_yob, 1980, 1990)) 
```

```{r}
bis_1 <- bis %>%
  select(animal_sex, animal_yob) %>%
  filter(between(animal_yob, 1980, 1990))  %>%
  filter(animal_sex == "M"|animal_sex=="F")
```

### How many makes and females

```{r}
males <- bis %>%
  select(animal_sex, animal_yob, animal_weight) %>%
  filter(between(animal_yob, 1980, 1990))  %>%
  filter(animal_sex == "M")
table(males$animal_sex)
```

```{r}
females <- bis %>%
  select(animal_sex, animal_yob, animal_weight) %>%
  filter(between(animal_yob, 1980, 1990))  %>%
  filter(animal_sex == "F")
table(females$animal_sex)
```


### Mean of Males
```{r}
mean(males$animal_weight)
```

```{r}
mean(females$animal_weight)
```

